# users/migrations/0003_populate_nationalities.py
from django.db import migrations


def create_nationalities(apps, schema_editor):
    Nationality = apps.get_model('arena_auth', 'Nationality')
    nationalities = [
        ('AF', 'Afghan'),
        ('AL', 'Albanian'),
        ('DZ', 'Algerian'),
        ('AS', 'American Samoan'),
        ('AD', 'Andorran'),
        ('AO', 'Angolan'),
        ('AI', 'Anguillan'),
        ('AQ', 'Antarctican'),
        ('AG', 'Antiguan or Barbudan'),
        ('AR', 'Argentinian'),
        ('AM', 'Armenian'),
        ('AW', 'Aruban'),
        ('AU', 'Australian'),
        ('AT', 'Austrian'),
        ('AZ', 'Azerbaijani'),
        ('BS', 'Bahamian'),
        ('BH', 'Bahraini'),
        ('BD', 'Bangladeshi'),
        ('BB', 'Barbadian'),
        ('BY', 'Belarusian'),
        ('BE', 'Belgian'),
        ('BZ', 'Belizean'),
        ('BJ', 'Beninese'),
        ('BM', 'Bermudian'),
        ('BT', 'Bhutanese'),
        ('BO', 'Bolivian'),
        ('BA', 'Bosnian or Herzegovinian'),
        ('BW', 'Botswanan'),
        ('BR', 'Brazilian'),
        ('BN', 'Bruneian'),
        ('BG', 'Bulgarian'),
        ('BF', 'Burkinabé'),
        ('BI', 'Burundian'),
        ('CV', 'Cabo Verdean'),
        ('KH', 'Cambodian'),
        ('CM', 'Cameroonian'),
        ('CA', 'Canadian'),
        ('KY', 'Caymanian'),
        ('CF', 'Central African'),
        ('TD', 'Chadian'),
        ('CL', 'Chilean'),
        ('CN', 'Chinese'),
        ('CO', 'Colombian'),
        ('KM', 'Comoran'),
        ('CG', 'Congolese (Congo-Brazzaville)'),
        ('CD', 'Congolese (Congo-Kinshasa)'),
        ('CR', 'Costa Rican'),
        ('CI', 'Ivorian'),
        ('HR', 'Croatian'),
        ('CU', 'Cuban'),
        ('CY', 'Cypriot'),
        ('CZ', 'Czech'),
        ('DK', 'Danish'),
        ('DJ', 'Djiboutian'),
        ('DM', 'Dominican'),
        ('DO', 'Dominican'),
        ('EC', 'Ecuadorian'),
        ('EG', 'Egyptian'),
        ('SV', 'Salvadoran'),
        ('GQ', 'Equatorial Guinean'),
        ('ER', 'Eritrean'),
        ('EE', 'Estonian'),
        ('SZ', 'Eswatini'),
        ('ET', 'Ethiopian'),
        ('FJ', 'Fijian'),
        ('FI', 'Finnish'),
        ('FR', 'French'),
        ('GA', 'Gabonese'),
        ('GM', 'Gambian'),
        ('GE', 'Georgian'),
        ('DE', 'German'),
        ('GH', 'Ghanaian'),
        ('GI', 'Gibraltarian'),
        ('GR', 'Greek'),
        ('GL', 'Greenlandic'),
        ('GD', 'Grenadian'),
        ('GU', 'Guamanian'),
        ('GT', 'Guatemalan'),
        ('GN', 'Guinean'),
        ('GW', 'Bissau-Guinean'),
        ('GY', 'Guyanese'),
        ('HT', 'Haitian'),
        ('HN', 'Honduran'),
        ('HU', 'Hungarian'),
        ('IS', 'Icelandic'),
        ('IN', 'Indian'),
        ('ID', 'Indonesian'),
        ('IR', 'Iranian'),
        ('IQ', 'Iraqi'),
        ('IE', 'Irish'),
        ('IL', 'Israeli'),
        ('IT', 'Italian'),
        ('JM', 'Jamaican'),
        ('JP', 'Japanese'),
        ('JO', 'Jordanian'),
        ('KZ', 'Kazakhstani'),
        ('KE', 'Kenyan'),
        ('KI', 'I-Kiribati'),
        ('KP', 'North Korean'),
        ('KR', 'South Korean'),
        ('KW', 'Kuwaiti'),
        ('KG', 'Kyrgyzstani'),
        ('LA', 'Lao'),
        ('LV', 'Latvian'),
        ('LB', 'Lebanese'),
        ('LS', 'Mosotho'),
        ('LR', 'Liberian'),
        ('LY', 'Libyan'),
        ('LI', 'Liechtensteiner'),
        ('LT', 'Lithuanian'),
        ('LU', 'Luxembourgish'),
        ('MG', 'Malagasy'),
        ('MW', 'Malawian'),
        ('MY', 'Malaysian'),
        ('MV', 'Maldivian'),
        ('ML', 'Malian'),
        ('MT', 'Maltese'),
        ('MH', 'Marshallese'),
        ('MR', 'Mauritanian'),
        ('MU', 'Mauritian'),
        ('MX', 'Mexican'),
        ('FM', 'Micronesian'),
        ('MD', 'Moldovan'),
        ('MC', 'Monegasque'),
        ('MN', 'Mongolian'),
        ('ME', 'Montenegrin'),
        ('MA', 'Moroccan'),
        ('MZ', 'Mozambican'),
        ('MM', 'Burmese'),
        ('NA', 'Namibian'),
        ('NR', 'Nauruan'),
        ('NP', 'Nepalese'),
        ('NL', 'Dutch'),
        ('NZ', 'New Zealander'),
        ('NI', 'Nicaraguan'),
        ('NE', 'Nigerien'),
        ('NG', 'Nigerian'),
        ('MK', 'Macedonian'),
        ('NO', 'Norwegian'),
        ('OM', 'Omani'),
        ('PK', 'Pakistani'),
        ('PW', 'Palauan'),
        ('PA', 'Panamanian'),
        ('PG', 'Papua New Guinean'),
        ('PY', 'Paraguayan'),
        ('PE', 'Peruvian'),
        ('PH', 'Filipino'),
        ('PL', 'Polish'),
        ('PT', 'Portuguese'),
        ('QA', 'Qatari'),
        ('RO', 'Romanian'),
        ('RU', 'Russian'),
        ('RW', 'Rwandan'),
        ('KN', 'Kittitian or Nevisian'),
        ('LC', 'Saint Lucian'),
        ('VC', 'Vincentian'),
        ('WS', 'Samoan'),
        ('SM', 'Sammarinese'),
        ('ST', 'Sao Tomean'),
        ('SA', 'Saudi'),
        ('SN', 'Senegalese'),
        ('RS', 'Serbian'),
        ('SC', 'Seychellois'),
        ('SL', 'Sierra Leonean'),
        ('SG', 'Singaporean'),
        ('SK', 'Slovak'),
        ('SI', 'Slovenian'),
        ('SB', 'Solomon Islander'),
        ('SO', 'Somali'),
        ('ZA', 'South African'),
        ('SS', 'South Sudanese'),
        ('ES', 'Spanish'),
        ('LK', 'Sri Lankan'),
        ('SD', 'Sudanese'),
        ('SR', 'Surinamese'),
        ('SE', 'Swedish'),
        ('CH', 'Swiss'),
        ('SY', 'Syrian'),
        ('TJ', 'Tajikistani'),
        ('TZ', 'Tanzanian'),
        ('TH', 'Thai'),
        ('TL', 'Timorese'),
        ('TG', 'Togolese'),
        ('TO', 'Tongan'),
        ('TT', 'Trinidadian or Tobagonian'),
        ('TN', 'Tunisian'),
        ('TR', 'Turkish'),
        ('TM', 'Turkmen'),
        ('TV', 'Tuvaluan'),
        ('UG', 'Ugandan'),
        ('UA', 'Ukrainian'),
        ('AE', 'Emirati'),
        ('GB', 'British'),
        ('US', 'American'),
        ('UY', 'Uruguayan'),
        ('UZ', 'Uzbekistani'),
        ('VU', 'Ni-Vanuatu'),
        ('VA', 'Vatican'),
        ('VE', 'Venezuelan'),
        ('VN', 'Vietnamese'),
        ('YE', 'Yemeni'),
        ('ZM', 'Zambian'),
        ('ZW', 'Zimbabwean'),
    ]
    for code, name in nationalities:
        Nationality.objects.create(code=code, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('arena_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_nationalities),
    ]
