# Generated by Django 5.0.6 on 2024-06-25 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_auth', '0002_populate_nationalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattr',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='arena_auth.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_attr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='arena_auth.userattr'),
        ),
    ]
