# Generated by Django 5.0.6 on 2024-06-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_auth', '0004_remove_customuser_user_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_attr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='arena_auth.userattr'),
        ),
    ]
