# Generated by Django 5.0.6 on 2024-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_auth', '0007_userattr_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattr',
            name='platform',
            field=models.CharField(blank=True, choices=[('PC', 'Pc'), ('Xbox', 'Xbox')], max_length=10, null=True),
        ),
    ]
