# Generated by Django 5.0.6 on 2024-07-05 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arena_auth', '0006_remove_customuser_user_attr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forza_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('performance_index', models.IntegerField()),
                ('speed', models.FloatField()),
                ('braking', models.FloatField()),
                ('handling', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('power_kW', models.IntegerField()),
                ('power_PS', models.IntegerField()),
                ('power_hp', models.IntegerField()),
                ('weight_kg', models.IntegerField()),
                ('weight_lb', models.IntegerField()),
                ('torque_Nm', models.IntegerField()),
                ('torque_ftlb', models.IntegerField()),
                ('traction', models.CharField(choices=[('FWD', 'Front-Wheel Drive'), ('RWD', 'Rear-Wheel Drive'), ('AWD', 'All-Wheel Drive')], max_length=10)),
                ('engine_position', models.CharField(choices=[('F', 'Front'), ('MF', 'Front-Mid'), ('MR', 'Rear-Mid'), ('R', 'Rear')], max_length=10)),
                ('Dsp', models.FloatField()),
                ('cfg', models.CharField(choices=[('E', 'E'), ('F', 'F'), ('I', 'I'), ('R', 'R'), ('V', 'V'), ('VR', 'VR'), ('W', 'W')], max_length=10)),
                ('cylinders', models.IntegerField()),
                ('ind', models.CharField(choices=[('DSC', 'DSC'), ('EV', 'EV'), ('NA', 'Naturally Aspirated'), ('T', 'T'), ('T4', 'T4'), ('TT', 'TT')], max_length=10)),
                ('wheel_type', models.CharField(choices=[('Factory', 'Factory'), ('Race', 'Race'), ('Upgraded', 'Upgraded')], max_length=10)),
                ('doors', models.IntegerField()),
                ('topless', models.BooleanField()),
                ('steering_position', models.CharField(choices=[('C', 'Central'), ('L', 'Left'), ('R', 'Right')], max_length=10)),
                ('dlc', models.BooleanField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena_auth.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('configuration', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('forza_id', models.IntegerField()),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena_auth.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('SingleRace', 'SingleRace'), ('Championship', 'Championship'), ('League', 'League')], max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progress', 'In progress'), ('Finished', 'Finished'), ('Deleted', 'Deleted')], default='Scheduled', max_length=20)),
                ('public', models.BooleanField(default=True)),
                ('ranked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=['event_documents/'])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progress', 'In progress'), ('Finished', 'Finished'), ('Deleted', 'Deleted')], default='Scheduled', max_length=20)),
                ('length', models.IntegerField()),
                ('weather', models.CharField(max_length=100)),
                ('race_start', models.DateTimeField()),
                ('qualification', models.TextField()),
                ('time_progress', models.CharField(choices=[('Continuous', 'Continuous'), ('Fixed', 'Fixed')], max_length=50)),
                ('timescale', models.CharField(max_length=4)),
                ('dynamic_tyre', models.BooleanField(default=False)),
                ('tyre_wear', models.FloatField()),
                ('dub_ghost', models.BooleanField(default=False)),
                ('penalty', models.CharField(choices=[('No', 'No'), ('Limited', 'Limited'), ('Moderate', 'Moderate'), ('Complete', 'Complete')], max_length=20)),
                ('disqualified', models.BooleanField(default=False)),
                ('box_stop', models.IntegerField()),
                ('multiclass', models.BooleanField(default=False)),
                ('multiclass_group_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('multiclass_group_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena_events.circuit')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='arena_events.event')),
            ],
        ),
        migrations.CreateModel(
            name='RaceCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_index', models.IntegerField()),
                ('division', models.CharField(max_length=255)),
                ('multiclass_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena_events.car')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena_events.race')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='cars',
            field=models.ManyToManyField(through='arena_events.RaceCar', to='arena_events.car'),
        ),
    ]
