# Generated by Django 5.0.6 on 2024-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dlc',
            field=models.CharField(max_length=255),
        ),
    ]
