# Generated by Django 5.0.6 on 2024-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_events', '0002_alter_car_dlc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racecar',
            old_name='division',
            new_name='classification',
        ),
        migrations.AddField(
            model_name='race',
            name='length_type',
            field=models.CharField(choices=[('Laps', 'Laps'), ('Minutes', 'Minutes')], default='race', max_length=20),
        ),
    ]
