# Generated by Django 5.0.6 on 2024-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_events', '0003_rename_division_racecar_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='collision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='tyre_on_track',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='weather',
            field=models.CharField(choices=[('Sunrise', 'Sunrise'), ('Morning', 'Morning'), ('Late morning', 'Late morning'), ('Noon', 'Noon'), ('Afternoon', 'Afternoon'), ('Late afternoon', 'Late afternoon'), ('Evening', 'Evening'), ('Sunset', 'Sunset'), ('Night', 'Night'), ('Midnight', 'Midnight')], max_length=100),
        ),
    ]
