# Generated by Django 5.0.6 on 2024-07-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena_events', '0004_race_collision_race_tyre_on_track_alter_race_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuit',
            old_name='nationality',
            new_name='country',
        ),
    ]
