# Generated by Django 5.0.6 on 2024-07-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_events', '0006_event_poster_race_initial_time_day_race_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='length_type',
            field=models.CharField(choices=[('Laps', 'Laps'), ('Minutes', 'Minutes')], default='Laps', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='timescale',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='tyre_on_track',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
