# Generated by Django 5.0.6 on 2024-07-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_events', '0008_eventmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='multiclass',
        ),
        migrations.RemoveField(
            model_name='race',
            name='multiclass_group_name1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='multiclass_group_name2',
        ),
        migrations.AddField(
            model_name='event',
            name='multiclass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='multiclass_group_name1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='multiclass_group_name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progress', 'In progress'), ('Finished', 'Finished'), ('Archived', 'Archived')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progress', 'In progress'), ('Finished', 'Finished'), ('Archived', 'Archived')], default='Scheduled', max_length=20),
        ),
    ]
