# Generated by Django 5.0.6 on 2024-07-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_events', '0009_remove_race_multiclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progress', 'In progress'), ('Finished', 'Finished'), ('Deleted', 'Deleted'), ('Archived', 'Archived')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progress', 'In progress'), ('Finished', 'Finished'), ('Deleted', 'Deleted'), ('Archived', 'Archived')], default='Scheduled', max_length=20),
        ),
    ]
