# Generated by Django 5.0.6 on 2024-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_events', '0010_alter_event_status_alter_race_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='start_time_game',
            new_name='custom_start_time',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='dynamic_tyre',
            new_name='dynamic_track_rubber',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='dub_ghost',
            new_name='ghost_backmarkers',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='tyre_on_track',
            new_name='start_track_rubber_level',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='tyre_wear',
            new_name='tire_wear',
        ),
        migrations.RemoveField(
            model_name='race',
            name='initial_time_day',
        ),
        migrations.RemoveField(
            model_name='race',
            name='length',
        ),
        migrations.RemoveField(
            model_name='race',
            name='length_type',
        ),
        migrations.RemoveField(
            model_name='race',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='racecar',
            name='multiclass_group_name',
        ),
        migrations.AddField(
            model_name='race',
            name='breaking_assist',
            field=models.CharField(choices=[('Assisted', 'Assisted'), ('ABS on', 'Abs On'), ('ABS off', 'Abs Off')], default='Assisted', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='forced_camera_view',
            field=models.CharField(choices=[('Assisted', 'None'), ('Bumper', 'Bumper'), ('Hood', 'Hood'), ('Cockpit', 'Cockpit'), ('Driver', 'Driver'), ('Chase Near', 'Chase Near'), ('Chase Far', 'Chase Far')], default='Assisted', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='game_type',
            field=models.CharField(choices=[('Circuit Race', 'Circuit Race'), ('Timed Race', 'Timed Race')], default='Circuit Race', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='number_of_laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='race_starting_time',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Sunrise', 'Sunrise'), ('Morning', 'Morning'), ('Late morning', 'Late Morning'), ('Noon', 'Noon'), ('Afternoon', 'Afternoon'), ('Late afternoon', 'Late Afternoon'), ('Evening', 'Evening'), ('Sunset', 'Sunset'), ('Night', 'Night'), ('Midnight', 'Midnight')], default='Late morning', max_length=100),
        ),
        migrations.AddField(
            model_name='race',
            name='race_timer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='shifting_assist',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Manual with Clutch only', 'Manual Clutch')], default='Automatic', max_length=25),
        ),
        migrations.AddField(
            model_name='race',
            name='steering_assist',
            field=models.CharField(choices=[('Full assisted', 'Fully'), ('Partially assisted', 'Partially'), ('Normal', 'Normal'), ('Simulation only', 'Simulation')], default='Full assisted', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='stm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='suggested_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='tcs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='throttle_assist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='racecar',
            name='multiclass_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('SingleRace', 'Singlerace'), ('Championship', 'Championship'), ('League', 'League')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progres', 'Progress'), ('Finished', 'Finished'), ('Deleted', 'Deleted'), ('Archived', 'Archived')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='box_stop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='penalty',
            field=models.CharField(choices=[('Off', 'Off'), ('Limited', 'Limited'), ('Moderate', 'Moderate'), ('Full', 'Full')], max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progres', 'Progress'), ('Finished', 'Finished'), ('Deleted', 'Deleted'), ('Archived', 'Archived')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='time_progress',
            field=models.CharField(choices=[('Rolling', 'Rolling'), ('Fixed', 'Fixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='weather',
            field=models.CharField(choices=[('Random', 'Random'), ('Variable', 'Variable'), ('Clear', 'Clear'), ('Mostly Clear', 'Mostly Clear'), ('Partly Cloudy', 'Partly Cloudy'), ('Cloudy', 'Cloudy'), ('Looming Clouds', 'Looming Clouds'), ('Thunderclouds', 'Thunderclouds'), ('Thin Haze', 'Thin Haze'), ('Patchy Fog', 'Patchy Fog'), ('Dense Fog', 'Dense Fog'), ('Overcast Dry', 'Overcast Dry'), ('Overcast Wet', 'Overcast Wet'), ('Drizzle', 'Drizzle'), ('Light Rain', 'Light Rain'), ('Moderate Rain', 'Moderate Rain'), ('Heavy rain', 'Heavy Rain'), ('Thunderstorm', 'Thunderstorm'), ('Rainstorm', 'Rainstorm')], max_length=100),
        ),
    ]
