# Generated by Django 5.0.6 on 2024-07-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_events', '0011_rename_start_time_game_race_custom_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='cars',
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff'), ('Pilot', 'Pilot')], default='Pilot', max_length=10),
        ),
        migrations.CreateModel(
            name='EventCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_index', models.IntegerField()),
                ('classification', models.CharField(max_length=255)),
                ('multiclass_group', models.IntegerField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena_events.car')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena_events.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='cars',
            field=models.ManyToManyField(through='arena_events.EventCar', to='arena_events.car'),
        ),
        migrations.DeleteModel(
            name='RaceCar',
        ),
    ]
