# Generated by Django 5.0.6 on 2024-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Member', 'Member'), ('Banned', 'Banned')], max_length=10),
        ),
    ]
